---
exclude-paths:
  - server/tests/
  - web/src/**/*.test.ts
  - web/src/**/*.test.tsx

exclude-patterns:
  - assert .*  # assert is standard in pytest tests

rules:
  "Avoid Use of Assert Statements":
    enabled: false
  "Placing a void expression inside another expression is forbidden":
    enabled: true
  "Returning a void expression from an arrow function shorthand is forbidden":
    enabled: true
  "Forbidden non-null assertion":
    enabled: false
  "Standard pseudo-random generators are not suitable for security":
    enabled: false
  "subprocess call - check for execution of untrusted input":
    enabled: false
  "Possible SQL injection vector through string-based query construction":
    enabled: false
  "Generic Object Injection Sink":
    enabled: false
  "Variable Assigned to Object Injection Sink":
    enabled: false
  "Non-HTML variable is used to store raw HTML":
    enabled: false
  "HTML passed in to function":
    enabled: false
  "This application allows user-controlled URLs to be passed directly to HTTP client libraries":
    enabled: false
  "The application dynamically constructs file or path information":
    enabled: false
